export const SHOP_ITEMS = [
    {
      slug: "tent",
      name: "TENT",
      price: "$110",
      image: "/images/homebase/tent.png",
      description: "Spacious waterproof tent perfect for 3–4 campers.",
      category: "home-base",
    },
    {
        slug: "canopy",
        name: "TENT CANOPY ADDITION",
        price: "$89",
        image: "/images/homebase/canopy.png",
        description: "Spacious waterproof tent perfect for 3–4 campers.",
        category: "home-base",
      },
      {
        slug: "sleeping-bag",
        name: "SLEEPING BAG",
        price: "$59",
        image: "/images/homebase/sleepingbag.png",
        description: "Spacious waterproof tent perfect for 3–4 campers.",
        category: "home-base",
      },
      {
        slug: "sleeping-mat",
        name: "SLEEPING MAT",
        price: "$49",
        image: "/images/homebase/mat.png",
        description: "Spacious waterproof tent perfect for 3–4 campers.",
        category: "home-base",
      },
      {
        slug: "tarp",
        name: "TARP",
        price: "$19",
        image: "/images/homebase/tarp.png",
        description: "Spacious waterproof tent perfect for 3–4 campers.",
        category: "home-base",
      },
      {
        slug: "wool-blanket",
        name: "WOOL BLANKET",
        price: "$34",
        image: "/images/homebase/blanket.png",
        description: "Spacious waterproof tent perfect for 3–4 campers.",
        category: "home-base",
      },
      {
        slug: "chair",
        name: "FOLDABLE CHAIR",
        price: "$39",
        image: "/images/homebase/chair.png",
        description: "Spacious waterproof tent perfect for 3–4 campers.",
        category: "home-base",
      },
      {
        slug: "table",
        name: "FOLDABLE TABLE",
        price: "$24",
        image: "/images/homebase/table.png",
        description: "Spacious waterproof tent perfect for 3–4 campers.",
        category: "home-base",
      },
      {
        slug: "pocket-blanket",
        name: "POCKET BLANKET",
        price: "$16",
        image: "/images/homebase/pocketblanket.png",
        description: "Spacious waterproof tent perfect for 3–4 campers.",
        category: "home-base",
      },
      {
        slug: "lantern",
        name: "SOLAR LANTERN/CHARGER",
        price: "$39",
        image: "/images/homebase/lantern.png",
        description: "Spacious waterproof tent perfect for 3–4 campers.",
        category: "home-base",
      },
      {
        slug: "flashlight",
        name: "FLASHLIGHT",
        price: "$9",
        image: "/images/homebase/flashlight.png",
        description: "Spacious waterproof tent perfect for 3–4 campers.",
        category: "home-base",
      },
      {
        slug: "fan",
        name: "SOLAR PORTABLE FAN",
        price: "$28",
        image: "/images/homebase/fan.png",
        description: "Spacious waterproof tent perfect for 3–4 campers.",
        category: "home-base",
      },
      {
        slug: "backpack",
        name: "HIKING BACKPACK",
        price: "$29",
        image: "/images/homebase/backpack.png",
        description: "Spacious waterproof tent perfect for 3–4 campers.",
        category: "home-base",
      },
      {
        slug: "hammock",
        name: "ENO HAMMOCK",
        price: "$49",
        image: "/images/homebase/hammock.png",
        description: "Spacious waterproof tent perfect for 3–4 campers.",
        category: "home-base",
      },
      {
        slug: "lounge",
        name: "INFLATABLE LOUNGE",
        price: "$89",
        image: "/images/homebase/lounge.png",
        description: "Spacious waterproof tent perfect for 3–4 campers.",
        category: "home-base",
      },
      {
        slug: "string-lights",
        name: "SOLAR STRING LIGHTS",
        price: "$29",
        image: "/images/homebase/stringlight.png",
        description: "Spacious waterproof tent perfect for 3–4 campers.",
        category: "home-base",
      },
      {
        slug: "first-aid",
        name: "FIRST AID KIT",
        price: "$15",
        image: "/images/homebase/firstaid.png",
        description: "Spacious waterproof tent perfect for 3–4 campers.",
        category: "home-base",
      },
      {
        slug: "candle",
        name: "CITRONELLA CANDLE",
        price: "$11",
        image: "/images/homebase/candle.png",
        description: "Spacious waterproof tent perfect for 3–4 campers.",
        category: "home-base",
      },
      {
        slug: "pocket-knife",
        name: "POCKET KNIFE",
        price: "$11",
        image: "/images/homebase/knife.png",
        description: "Spacious waterproof tent perfect for 3–4 campers.",
        category: "home-base",
      },
      {
        slug: "compass",
        name: "COMPASS",
        price: "$6",
        image: "/images/homebase/compass.png",
        description: "Spacious waterproof tent perfect for 3–4 campers.",
        category: "home-base",
      },


      {
        slug: "stove",
        name: "PORTABLE STOVE SET",
        price: "$69",
        image: "/images/cookclean/stove.png",
        description: "Spacious waterproof tent perfect for 3–4 campers.",
        category: "cook + clean",
      },
      {
        slug: "lighter",
        name: "LIGHTER",
        price: "$9",
        image: "/images/cookclean/lighter.png",
        description: "Spacious waterproof tent perfect for 3–4 campers.",
        category: "cook + clean",
      },
      {
        slug: "mess-kit",
        name: "MESS KIT",
        price: "$19",
        image: "/images/cookclean/messkit.png",
        description: "Spacious waterproof tent perfect for 3–4 campers.",
        category: "cook + clean",
      },
      {
        slug: "kettle",
        name: "KETTLE",
        price: "$17",
        image: "/images/cookclean/kettle.png",
        description: "Spacious waterproof tent perfect for 3–4 campers.",
        category: "cook + clean",
      },
      {
        slug: "grill",
        name: "CAMP FIRE GRILL",
        price: "$24",
        image: "/images/cookclean/grill.png",
        description: "Spacious waterproof tent perfect for 3–4 campers.",
        category: "cook + clean",
      },
      {
        slug: "roasting-sticks",
        name: "ROASTING STICKS",
        price: "$19",
        image: "/images/cookclean/sticks.png",
        description: "Spacious waterproof tent perfect for 3–4 campers.",
        category: "cook + clean",
      },
      {
        slug: "towel",
        name: "QUICK DRY TOWEL",
        price: "$19",
        image: "/images/cookclean/towel.png",
        description: "Spacious waterproof tent perfect for 3–4 campers.",
        category: "cook + clean",
      },
      {
        slug: "water-bottle",
        name: "WATER BOTTLE",
        price: "$13",
        image: "/images/cookclean/bottle.png",
        description: "Spacious waterproof tent perfect for 3–4 campers.",
        category: "cook + clean",
      },


    {
      slug: "badminton",
      name: "BADMINTON SET",
      price: "$39",
      image: "/images/fun/badminton.png",
      description: "Cozy up with this bundle of silly + surprising prompts.",
      category: "fun + games",
    },
    {
        slug: "washers",
        name: "WASHER SET",
        price: "$39",
        image: "/images/fun/washer.png",
        description: "Cozy up with this bundle of silly + surprising prompts.",
        category: "fun + games",
      },
      {
        slug: "cornhole",
        name: "CORNHOLE SET",
        price: "$39",
        image: "/images/fun/cornhole.png",
        description: "Cozy up with this bundle of silly + surprising prompts.",
        category: "fun + games",
      },
      {
        slug: "ring",
        name: "RING SWING GAME",
        price: "$22",
        image: "/images/fun/ring.png",
        description: "Cozy up with this bundle of silly + surprising prompts.",
        category: "fun + games",
      },
      {
        slug: "bocce",
        name: "BOCCE BALL SET",
        price: "$39",
        image: "/images/fun/bocce.png",
        description: "Cozy up with this bundle of silly + surprising prompts.",
        category: "fun + games",
      },
      {
        slug: "jenga",
        name: "GIANT JENGA SET",
        price: "$39",
        image: "/images/fun/jenga.png",
        description: "Cozy up with this bundle of silly + surprising prompts.",
        category: "fun + games",
      },
      {
        slug: "telescope",
        name: "PORTABLE TELESCOPE",
        price: "$39",
        image: "/images/fun/telescope.png",
        description: "Cozy up with this bundle of silly + surprising prompts.",
        category: "fun + games",
      },
      {
        slug: "card",
        name: "CAMPFIRE CARD GAMES",
        price: "$39",
        image: "/images/fun/badminton.png",
        description: "Cozy up with this bundle of silly + surprising prompts.",
        category: "fun + games",
      },
      {
        slug: "airpump",
        name: "ELECTRIC AIR PUMP",
        price: "$29",
        image: "/images/fun/airpump.png",
        description: "Cozy up with this bundle of silly + surprising prompts.",
        category: "fun + games",
      },
      {
        slug: "tube",
        name: "INFLATABLE TUBE",
        price: "$29",
        image: "/images/fun/tube.png",
        description: "Cozy up with this bundle of silly + surprising prompts.",
        category: "fun + games",
      },
      {
        slug: "drinktube",
        name: "DRINK COOLER TUBE",
        price: "$39",
        image: "/images/fun/drinktube.png",
        description: "Cozy up with this bundle of silly + surprising prompts.",
        category: "fun + games",
      },
      {
        slug: "cooler",
        name: "SOFT COOLER",
        price: "$29",
        image: "/images/fun/cooler.png",
        description: "Cozy up with this bundle of silly + surprising prompts.",
        category: "fun + games",
      },
      {
        slug: "towel",
        name: "BEACH TOWEL - Set of 4",
        price: "$39",
        image: "/images/fun/towel.png",
        description: "Cozy up with this bundle of silly + surprising prompts.",
        category: "fun + games",
      },
      {
        slug: "beachchair",
        name: "BEACH CHAIR",
        price: "$24",
        image: "/images/fun/beachchair.png",
        description: "Cozy up with this bundle of silly + surprising prompts.",
        category: "fun + games",
      },
      {
        slug: "umbrella",
        name: "UMBRELLA ATTACHMENT",
        price: "$39",
        image: "/images/fun/umbrella.png",
        description: "Cozy up with this bundle of silly + surprising prompts.",
        category: "fun + games",
      },
      {
        slug: "crytals",
        name: "COLOR FIRE CRYSTALS",
        price: "$39",
        image: "/images/fun/crystals.png",
        description: "Cozy up with this bundle of silly + surprising prompts.",
        category: "fun + games",
      },
]
